### ISSUE TITLE
Add Superset results into a fatal error

### ISSUE THREAD

**Issue by lestremm** [amundsen-io/amundsen#974]
I've tried to add Apache Superset for previewing in Amundsen. I've followed the following installation guide / tutorial:

https://www.amundsen.io/amundsen/tutorials/data-preview-with-superset/

and especially this guide:

https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/examples/superset_preview_client.md

## Expected Behavior
I would expected that the setting

`entry_points="""
    ...

    [preview_client]
    table_preview_client_class = amundsen_application.base.examples.example_superset_preview_client:SupersetPreviewClient
"""`

will result in an active preview button after after the following command and restart

`python3 setup.py install`

## Current Behavior
I get the following error in the setup process

`ast27/Parser/acceler.c:13:10: fatal error: pgenheaders.h: Datei oder Verzeichnis nicht gefunden
   13 | #include "pgenheaders.h"
      |          ^~~~~~~~~~~~~~~
`

I assume that this is an python version issue (I used python 3.8 for venv).

## Possible Solution
I've googled some around and it seams that it doenst work with python 3.8 and the typed-ast library needs to be updated.

[https://stackoverflow.com/questions/59920177/cant-get-a-simply-django-app-to-build-on-docker-must-have-postgres-mysql-sup](url)

I'v tried this by changing the requirements.txt but it doenst work. I think a fix in the source code is needed. Furtermore I've tried to build the venv with an older python version (3.5) but I'm not really an python expert and the pip3 command still revers to python 3.8 in the venv.

## Steps to Reproduce
1. Follow above instruvtions on Ubuntu 18 with python 3.8

## Your Environment
* Amunsen version used: current
* OS: happens in Windows 10 and current Ubuntu Version

**Comment by MarcoFranchin96** [comment]
I would like to ask you a question because I can't either configure the preview.

Have you modified something in the file "examples.example_superset_preview_client"?
After I run python3 setup.py with che cahnges in the entry point, and restart the frontend docker, nothing change in the datacatalog.
